//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestEcole.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devoir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devoir()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateDevoir { get; set; }
        public System.DateTime DatePublication { get; set; }
        public double Coefficient { get; set; }
        public int Matiere_Id { get; set; }
        public int Formateur_Id { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Matiere Matiere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
    }
}
