//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestEcole.Api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestEcoleEntities : DbContext
    {
        public GestEcoleEntities()
            : base("name=GestEcoleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Devoir> Devoirs { get; set; }
        public virtual DbSet<Groupe> Groupes { get; set; }
        public virtual DbSet<Matiere> Matieres { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
