//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestEcole.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Devoir_Id { get; set; }
        public int Eleve_Id { get; set; }
        public double Valeur { get; set; }
    
        public virtual Devoir Devoir { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
